export const PRE_DEFINED_BUILDING_COLORS = [
  { label: "White", value: "white" },
  { label: "Red", value: "#FF5733" },
  { label: "Green", value: "#33FF57" },
  { label: "Blue", value: "#3357FF" },
  { label: "Pink", value: "#FF33A1" },
  { label: "Purple", value: "#A133FF" },
  { label: "Cyan", value: "#33FFF5" },
  { label: "Yellow", value: "#F5FF33" },
  { label: "Orange", value: "#FF8C33" },
  { label: "Violet", value: "#8C33FF" },
  { label: "Light Green", value: "#33FF8C" },
  { label: "Gold", value: "#FFD700" },
  { label: "Crimson", value: "#DC143C" },
  { label: "Dark Turquoise", value: "#00CED1" },
  { label: "Orange Red", value: "#FF4500" },
  { label: "Sea Green", value: "#2E8B57" },
  { label: "Saddle Brown", value: "#8B4513" },
  { label: "Light Sea Green", value: "#20B2AA" },
  { label: "Medium Slate Blue", value: "#7B68EE" },
  { label: "Green Yellow", value: "#ADFF2F" },
  { label: "Deep Pink", value: "#FF1493" },
];
